stages:
  autoencoder:
    cmd: python src/autoencoder.py src/FCDataset.py
    deps:
    - src/FCDataset.py
    - src/autoencoder.py
    params:
    - autoencoder
    outs:
    - encoded_data.npy
  clusterizer:
    cmd: python src/clusterizer.py encoded_data.npy
    deps:
    - encoded_data.npy
    - src/clusterizer.py
    params:
    - autoencoder.seed
    outs:
    - submission.csv

artifacts:
  autoencoder:
    path: model.pd
    type: model
plots:
- plots/loss.csv:
    x: step
    y: [train_loss, test_loss]
metrics:
- dvclive/metrics.json
