stages:
  preprocess:
    cmd: python scripts/preprocessing.py ../contest-data.npy
    deps:
    - ../contest-data.npy
    - scripts/preprocessing.py
    params:
    - preprocess.seed
    outs:
    - transformed-data/corr-data.npy
    - transformed-data/preprocessed-data.npy
  heatmap:
    cmd: python scripts/heatmap.py transformed-data/corr-data.npy
    deps:
    - scripts/heatmap.py
    - transformed-data/corr-data.npy
    outs:
    - heatmaps/corr-matrix-0.png
    - heatmaps/corr-matrix-1.png
    - heatmaps/corr-matrix-2.png
    - heatmaps/corr-matrix-3.png
    - heatmaps/corr-matrix-4.png
    - heatmaps/corr-matrix-5.png
    - heatmaps/corr-matrix-6.png
    - heatmaps/corr-matrix-7.png
    - heatmaps/corr-matrix-8.png
    - heatmaps/corr-matrix-9.png
    - heatmaps/corr-matrix-10.png
    - heatmaps/corr-matrix-11.png
    - heatmaps/corr-matrix-12.png
    - heatmaps/corr-matrix-13.png
    - heatmaps/corr-matrix-14.png
    - heatmaps/corr-matrix-15.png
    - heatmaps/corr-matrix-16.png
    - heatmaps/corr-matrix-17.png
    - heatmaps/corr-matrix-18.png
    - heatmaps/corr-matrix-19.png