stages:
  autoencoder:
    cmd: python src/autoencoder.py src/FCDataset.py
    deps:
    - src/FCDataset.py
    - src/autoencoder.py
    params:
    - architecture.hid1_dim
    - architecture.hid2_dim
    - architecture.out_dim
    - architecture.p
    - optimizer.beta1
    - optimizer.beta2
    - optimizer.eps
    - optimizer.lr
    - optimizer.num_epochs
    - optimizer.weight_decay
    - seed
    outs:
    - encoded_data.npy
  clusterizer:
    cmd: python src/clusterizer.py encoded_data.npy
    deps:
    - encoded_data.npy
    - src/clusterizer.py
    outs:
    - submission.csv

artifacts:
  autoencoder:
    path: model.pd
    type: model
metrics:
- dvclive/metrics.json
plots:
- plots/metrics.csv:
    x: step
    y: train_loss test_loss
