autoencoder:
  seed: 444
  architecture:
    hid_dim: 300
    out_dim: 25
    drop_prob: 0.5
  optimizer:
    lr: 0.001
    beta1: 0.9
    beta2: 0.999
    eps: 0.00000001
    weight_decay: 0.000001
  num_epochs: 100

