stages:
  ConvNet:
    cmd: python src/ConvNet.py src/Datasets.py
    deps:
    - src/ConvNet.py
    - src/Datasets.py
    params:
    - net_seed
    - net_architecture
    - net_optimizer
    - net_threshold
plots:
- plots/loss.csv:
    x: step
    y: [train_loss, test_loss]
    title: Loss
- plots/accuracy.csv:
    x: step
    y: [train_accuracy, test_accuracy]
    title: Accuracy
- plots/precision.csv:
    x: step
    y: [train_precision, test_precision]
    title: Precision
- plots/recall.csv:
    x: step
    y: [train_recall, test_recall]
    title: Recall
- plots/f1.csv:
    x: step
    y: [train_f1, test_f1]
    title: F1
- dvclive/plots/custom/train_confusion_matrix.json:
    template: confusion
    x: true_lab
    y: pred_lab
    title: Confusion matrix for train set
    x_label: Ground truth value
    y_label: Predicted value
- dvclive/plots/custom/test_confusion_matrix.json:
    template: confusion
    x: true_lab
    y: pred_lab
    title: Confusion matrix for test set
    x_label: Ground truth value
    y_label: Predicted value
- dvclive/plots/custom/train_roc.json:
    template: linear
    x: fp
    y: tp
    title: ROC for train set
- dvclive/plots/custom/test_roc.json:
    template: linear
    x: fp
    y: tp
    title: ROC for test set
artifacts:
  ConvNet:
    path: model.pd
    type: model
metrics:
- dvclive/metrics.json
